# Chapter 5

### 5.1 Pendahuluan

In [1]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a. shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.itemsize

4

In [6]:
a.size

15

In [7]:
type(a)

numpy.ndarray

In [9]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

### 5.2 Membuat Array

In [11]:
import numpy as np
a=np.array([2,3,4])
a

array([2, 3, 4])

In [12]:
a.dtype

dtype('int32')

In [13]:
b=np.array ([1.2,3.5,5.1])
b.dtype

dtype('float64')

In [14]:
b=np.array([(1.5,2,3),(4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [15]:
c=np.array([[1,2],[3,4] ], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [16]:
np. zeros ( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np. ones ( (2,3,4) , dtype=np.int16) # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [18]:
np. empty((2,3)) #uninitialized, output may vary

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [19]:
np. arange (10,30,5)

array([10, 15, 20, 25])

In [22]:
np. arange (0 ,2 ,0.3) # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [25]:
from numpy import pi
np. linspace (0 ,2 ,9) #9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [26]:
x=np.linspace (0 ,2*pi, 100) #useful to evaluate function at lots of points
f=np.sin(x)

### 5.3 Menampilkan Array

In [27]:
a=np.arange(6) #1d array
print (a)

[0 1 2 3 4 5]


In [29]:
b=np. arange (12).reshape (4,3) #2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [30]:
print (np. arange (10000))

[   0    1    2 ... 9997 9998 9999]


In [31]:
print (np. arange (10000). reshape (100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [32]:
np. set_printoptions ( threshold = 3)